function createfigure(YData1, XData1, CData1, YData2, XData2, CData2, CData3, CData4)
%CREATEFIGURE(YData1, XData1, CData1, YData2, XData2, CData2, CData3, CData4)
%  YDATA1:  patch ydata
%  XDATA1:  patch xdata
%  CDATA1:  patch cdata
%  YDATA2:  patch ydata
%  XDATA2:  patch xdata
%  CDATA2:  patch cdata
%  CDATA3:  patch cdata
%  CDATA4:  patch cdata

%  Auto-generated by MATLAB on 08-Apr-2024 12:02:55

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,3,1,'Tag','Uplane','Parent',figure1);
axis off

% Create patch
patch('Tag','planeU','Parent',subplot1,'YData',YData1,'XData',XData1,...
    'CData',CData1,...
    'FaceColor','flat',...
    'EdgeColor','none',...
    'FaceVertexCData',CData1);

% Create xlabel
xlabel('U-matrix','VerticalAlignment','top','Visible','on');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0.49 6.01]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0.33 10.67]);
axis(subplot1,'ij');
% Set the remaining axes properties
set(subplot1,'DataAspectRatio',[0.9015 1 1],'PlotBoxAspectRatio',...
    [3.06156405990017 5.17 1],'XAxisLocation','top');
% Create colorbar
colorbar(subplot1);

% Create subplot
subplot2 = subplot(2,3,2,'Tag','Cplane','Parent',figure1);
axis off

% Create patch
patch('Tag','planeC','Parent',subplot2,'YData',YData2,'XData',XData2,...
    'CData',CData2,...
    'FaceColor','flat',...
    'EdgeColor','none',...
    'FaceVertexCData',CData2);

% Create xlabel
xlabel('thermalmassroof','VerticalAlignment','top','Visible','on');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0.49 6.01]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[0.33 10.67]);
axis(subplot2,'ij');
% Set the remaining axes properties
set(subplot2,'DataAspectRatio',[0.9015 1 1],'PlotBoxAspectRatio',...
    [3.06156405990017 5.17 1],'XAxisLocation','top');
% Create colorbar
colorbar(subplot2);

% Create subplot
subplot3 = subplot(2,3,3,'Tag','Cplane','Parent',figure1);
axis off

% Create patch
patch('Tag','planeC','Parent',subplot3,'YData',YData2,'XData',XData2,...
    'CData',CData3,...
    'FaceColor','flat',...
    'EdgeColor','none',...
    'FaceVertexCData',CData3);

% Create xlabel
xlabel('Twall','VerticalAlignment','top','Visible','on');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[0.49 6.01]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[0.33 10.67]);
axis(subplot3,'ij');
% Set the remaining axes properties
set(subplot3,'DataAspectRatio',[0.9015 1 1],'PlotBoxAspectRatio',...
    [3.06156405990017 5.17 1],'XAxisLocation','top');
% Create colorbar
colorbar(subplot3);

% Create subplot
subplot4 = subplot(2,3,4,'Tag','Cplane','Parent',figure1);
axis off

% Create patch
patch('Tag','planeC','Parent',subplot4,'YData',YData2,'XData',XData2,...
    'CData',CData4,...
    'FaceColor','flat',...
    'EdgeColor','none',...
    'FaceVertexCData',CData4);

% Create xlabel
xlabel('masslaw','VerticalAlignment','top','Visible','on');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot4,[0.49 6.01]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot4,[0.33 10.67]);
axis(subplot4,'ij');
% Set the remaining axes properties
set(subplot4,'DataAspectRatio',[0.9015 1 1],'PlotBoxAspectRatio',...
    [3.06156405990017 5.17 1],'XAxisLocation','top');
% Create colorbar
colorbar(subplot4);

% Create subplot
subplot5 = subplot(2,3,5,'Tag','Cplane','Parent',figure1);
axis off

% Create patch
patch('Tag','planeC','Parent',subplot5,'YData',YData2,'XData',XData2,...
    'FaceColor','none');

% Create xlabel
xlabel('Labels','VerticalAlignment','top','Visible','on');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot5,[0.49 6.01]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot5,[0.33 10.67]);
axis(subplot5,'ij');
% Set the remaining axes properties
set(subplot5,'DataAspectRatio',[0.9015 1 1],'PlotBoxAspectRatio',...
    [3.06156405990017 5.17 1],'XAxisLocation','top');
